### ISSUE TITLE
boxes AssertionError

### ISSUE THREAD

**Issue by xxxzhi** [scwangdyd/zero_shot_hoi#9]
python train_net.py --num-gpus 1   --config-file configs/HICO-DET/interaction_R_50_FPN.yaml OUTPUT_DIR ./output/HICO_interaction

ERROR [09/08 16:54:57 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):                   
  File "/opt/data/private/Code/detectron2/detectron2/engine/train_loop.py", line 141, in train
    self.run_step()                                                     
  File "/opt/data/private/Code/detectron2/detectron2/engine/train_loop.py", line 227, in run_step
    loss_dict = self.model(data)                     
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)      
  File "/opt/data/private/Code/zero_shot_hoi/lib/arch.py", line 127, in forward               
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)                
  File "/opt/data/private/Code/zero_shot_hoi/lib/modeling/horpn.py", line 369, in forward        
    losses = {k: v * self.loss_weight for k, v in outputs.losses().items()}
  File "/opt/data/private/Code/zero_shot_hoi/lib/modeling/horpn_outputs.py", line 509, in losses
    gts = self._get_ground_truth()                                                      
  File "/opt/data/private/Code/zero_shot_hoi/lib/modeling/horpn_outputs.py", line 389, in _get_ground_truth
    anchors = [Boxes.cat(anchors_i) for anchors_i in self.anchors]      
  File "/opt/data/private/Code/zero_shot_hoi/lib/modeling/horpn_outputs.py", line 389, in <listcomp>
    anchors = [Boxes.cat(anchors_i) for anchors_i in self.anchors]         
  File "/opt/data/private/Code/detectron2/detectron2/structures/boxes.py", line 291, in cat     
    assert isinstance(boxes_list, (list, tuple))
AssertionError

**Comment by byrsongyuxin** [comment]
Have you solved this problem?
